# Generated by Django 3.1.4 on 2020-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20201211_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a short description of the book.', max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
