# Generated by Django 3.1.4 on 2020-12-12 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0009_auto_20201212_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book', to=settings.AUTH_USER_MODEL),
        ),
    ]
