# Generated by Django 3.1.4 on 2020-12-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
