# Generated by Django 3.1.4 on 2020-12-13 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0019_auto_20201213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecommentuser',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user_table', to='manager.comment'),
        ),
        migrations.AlterField(
            model_name='likecommentuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
