# Generated by Django 3.1.4 on 2020-12-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0021_auto_20201215_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='rate'),
        ),
        migrations.CreateModel(
            name='RateBookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_rate', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='book_user_rate')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user_table', to='manager.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_book_table', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ratebookuser',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='rate_unique_book_user'),
        ),
    ]
