# Generated by Django 3.1.4 on 2020-12-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20201216_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rate',
            new_name='user_rate',
        ),
        migrations.AlterField(
            model_name='ratebookuser',
            name='book_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='book_user_rate'),
        ),
    ]
