# Generated by Django 3.1.4 on 2020-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20201216_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratebookuser',
            name='book_rate',
        ),
        migrations.AddField(
            model_name='ratebookuser',
            name='user_book_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='user_book_rate'),
        ),
    ]
