# Generated by Django 3.1.4 on 2020-12-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_ratebookuser_users_rate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratebookuser',
            name='users_rate_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
