# Generated by Django 3.1.4 on 2020-12-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20201216_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratebookuser',
            name='users_rate_count',
        ),
        migrations.AddField(
            model_name='book',
            name='users_rate_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
