# Generated by Django 3.1.4 on 2020-12-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20201216_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('result', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
        migrations.RenameField(
            model_name='ratebookuser',
            old_name='user_book_rate',
            new_name='user_book_score',
        ),
    ]
