# Generated by Django 3.1.4 on 2020-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20201217_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='user',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
