# Generated by Django 3.1.4 on 2020-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_testclass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testclass',
            name='num',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
