# Generated by Django 3.1.4 on 2020-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_auto_20201217_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_rate',
        ),
        migrations.RemoveField(
            model_name='ratebookuser',
            name='user_book_score',
        ),
        migrations.AddField(
            model_name='book',
            name='users_rate_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='ratebookuser',
            name='user_rate_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='user_book_rate'),
        ),
    ]
