# Generated by Django 3.1.4 on 2020-12-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_auto_20201218_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='LikeBookUser',
        ),
    ]
